import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from './Components/Header';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>#VemSerDBC</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header/>

      <main className={styles.main}>
        <h1>Início</h1>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perferendis omnis officia cupiditate hic repellat veritatis consectetur necessitatibus? Rerum at veritatis vel soluta, minus tempore deserunt ullam impedit architecto voluptas, dolore id! Nemo illum doloremque ex possimus amet fuga suscipit accusamus.</p>
      </main>

    </div>
  )
}
